version: '2'
services:
  e2e:
    image: casperlai/docker-webdriverio:latest
    depends_on:
      - chrome
      - firefox

  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    container_name: hub

  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5901:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5900:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
